import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const barlow = localFont({
  src: [
    {
      path: "../public/fonts/Barlow/Barlow-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Barlow/Barlow-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Barlow/Barlow-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    // Add more weights/styles as needed
  ],
  variable: "--barlow",
});

const modular_amplitude = localFont({
  src: [
    {
      path: "../public/fonts/ModularAmplitude/Modular_Amplitude.otf",
      weight: "400",
      style: "normal",
    },

    // Add more weights/styles as needed
  ],
  variable: "--modularAmplitude",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${barlow.variable} ${modular_amplitude.variable} antialiased flex  flex-col min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
