export const angular3DHeadButtons = [
  { imageUrl: "/assets/heart.svg" },
  { imageUrl: "/assets/send.svg" },
  { imageUrl: "/assets/comment.svg" },
  { imageUrl: "/assets/filter.svg" },
];

export const pageLinks = [
  { pagename: "A1_1", href: "a1/1stscreen" },
  { pagename: "A1_2", href: "a1/2ndscreen" },
  { pagename: "A1_3", href: "a1/3rdscreen" },
  { pagename: "A2_1", href: "a2/1stscreen" },
  { pagename: "A2_2", href: "a2/2ndscreen" },
  { pagename: "A2_3", href: "a2/3rdscreen" },
  { pagename: "A3_1", href: "a3/1stscreen" },
  { pagename: "A3_2", href: "a3/2ndscreen" },
  { pagename: "A4_1", href: "a4/1stscreen" },
  { pagename: "A4_2", href: "a4/2ndscreen" },
  { pagename: "A4_3", href: "a4/3rdscreen" },
  { pagename: "A4_4", href: "a4/4thscreen" },
  { pagename: "A4_5", href: "a4/5thscreen" },
  { pagename: "A4_6", href: "a4/6thscreen" },
  { pagename: "A4_7", href: "a4/7thscreen" },
  { pagename: "A5_1", href: "a5/1stscreen" },
  { pagename: "A5_2", href: "a5/2ndscreen" },
  { pagename: "A6_1", href: "a6/1stscreen" },
  { pagename: "A6_2", href: "a6/2ndscreen" },
  { pagename: "A7_1", href: "a7/1stscreen" },
  { pagename: "A7_2", href: "a7/2ndscreen" },
  { pagename: "A8_1", href: "a8/1stscreen" },
];
