export const angular3DHeadButtons = [
  { imageUrl: "/assets/heart.svg" },
  { imageUrl: "/assets/send.svg" },
  { imageUrl: "/assets/comment.svg" },
  { imageUrl: "/assets/filter.svg" },
];

export const matchName = [
  { name: "Alice" },
  { name: "Molly" },
  { name: "Vi" },
  { name: "Lina" },
  { name: "Joanna" },
];

export const matchName2 = [
  { name: "Anna" },
  { name: "Debbie" },
  { name: "Nicole" },
  { name: "Anna" },
  { name: "Ruth" },
];
export const matchName3 = [
  { name: "Dianne", age: 19 },
  { name: "Jane", age: 21 },
  { name: "Betty", age: 24 },
  { name: "Sarah", age: 22 },
  { name: "Julie", age: 21 },
  { name: "Regina", age: 21 },
  { name: "Emily", age: 20 },
  { name: "Hannah", age: 25 },
  { name: "Olivia", age: 23 },
];

export const backgroundImageCardNames = [
  { name: "Victoria", age: 19 },
  { name: "Arthur", age: 19 },
  { name: "James", age: 26 },
  { name: "Kristin", age: 21 },
  { name: "Joanna", age: 23 },
  { name: "Courtney", age: 23 },
  { name: "Leslie", age: 23 },
  { name: "Eduardo", age: 22 },
  { name: "Aubrey", age: 24 },
  { name: "Philip", age: 25 },
  { name: "Kylie", age: 18 },
  { name: "Shawn", age: 27 },
  { name: "Shawn", age: 24 },
  { name: "Courtney", age: 23 },
  { name: "Leslie", age: 23 },
];

export const feelingsList = [
  "Anxiety",
  "Calm",
  "Joy",
  "Anger",
  "Sadness",
  "Confusion",
  "Frustration",
  "Guilt",
  "Relief",
  "Inspired",
  "Pride",
  "Stress",
  "Tired",
  "Loneliness",
  "Disappointment",
  "Fear",

  "Surprise",
  "Disgust",
  "Sorrow",
  "Bitterness",
  "Numbness",
  "Insecure",
  "Gratitude",
  "Relaxed",
  "Empowered",
  "Anguish",
  "Bored",
  "Despair",
  "Euphoric",
  "Hopeful",
  "Nostalgic",
  "Energized",
  "Inspired",
  "Content",
  "Curious",
];

export const pageLinks = [
  { pagename: "A1_1", href: "a1/1stscreen" },
  { pagename: "A1_2", href: "a1/2ndscreen" },
  { pagename: "A1_3", href: "a1/3rdscreen" },
  { pagename: "A2_1", href: "a2/1stscreen" },
  { pagename: "A2_2", href: "a2/2ndscreen" },
  { pagename: "A2_3", href: "a2/3rdscreen" },
  { pagename: "A3_1", href: "a3/1stscreen" },
  { pagename: "A3_2", href: "a3/2ndscreen" },
  { pagename: "A4_1", href: "a4/1stscreen" },
  { pagename: "A4_2", href: "a4/2ndscreen" },
  { pagename: "A4_3", href: "a4/3rdscreen" },
  { pagename: "A4_4", href: "a4/4thscreen" },
  { pagename: "A4_5", href: "a4/5thscreen" },
  { pagename: "A4_6", href: "a4/6thscreen" },
  { pagename: "A4_7", href: "a4/7thscreen" },
  { pagename: "A5_1", href: "a5/1stscreen" },
  { pagename: "A5_2", href: "a5/2ndscreen" },
  { pagename: "A6_1", href: "a6/1stscreen" },
  { pagename: "A6_2", href: "a6/2ndscreen" },
  { pagename: "A7_1", href: "a7/1stscreen" },
  { pagename: "A7_2", href: "a7/2ndscreen" },
  { pagename: "A8_1", href: "a8/1stscreen" },
  { pagename: "A8_2", href: "a8/2ndscreen" },
  { pagename: "A9_1", href: "a9/1stscreen" },
  { pagename: "A9_2", href: "a9/2ndscreen" },
  { pagename: "A9_3", href: "a9/3rdscreen" },
  { pagename: "A10_1", href: "a10/1stscreen" },
  { pagename: "A10_2", href: "a10/2ndscreen" },
  { pagename: "A10_3", href: "a10/3rdscreen" },
  { pagename: "A10_4", href: "a10/4thscreen" },
  { pagename: "A11_1", href: "a11/1stscreen" },
  { pagename: "A11_2", href: "a11/2ndscreen" },
  { pagename: "A12_1", href: "a12/1stscreen" },
  { pagename: "A12_2", href: "a12/2ndscreen" },
  { pagename: "A13_1", href: "a13/1stscreen" },
  { pagename: "A13_2", href: "a13/2ndscreen" },
  { pagename: "A13_3", href: "a13/3rdscreen" },
  { pagename: "A13_4", href: "a13/4thscreen" },
  { pagename: "A14_1", href: "a14/1stscreen" },
  { pagename: "A14_2", href: "a14/2ndscreen" },
  { pagename: "A14_3", href: "a14/3rdscreen" },
  { pagename: "A14_4", href: "a14/4thscreen" },
  { pagename: "A15_1", href: "a15/1stscreen" },
  { pagename: "A15_2", href: "a15/2ndscreen" },
  { pagename: "A15_3", href: "a15/3rdscreen" },
  { pagename: "A15_4", href: "a15/4thscreen" },
  { pagename: "A15_5", href: "a15/5thscreen" },
  { pagename: "A16_1", href: "a16/1stscreen" },
];
